Events features
MenendezON/math-magicians pull request #3
Opened 2023-08-09 14:33 UTC by MenendezON

This pull request concerns the implementation of the event of each button in our Calculator app based on React.

2023-08-09 15:05 UTC, Ibizugbe requested changes
Hi @MenendezON 👋🏼👋🏼👋🏼👋🏼, 

![require_changes](https://github.com/MenendezON/math-magicians/assets/64643995/69ee98b1-fe06-4689-bba7-f8655dd74762)


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are passing👍🏼.
- [x] Gitflow is used👍🏼.
- [x] the `calculate` and `operate` files are used as required👍🏼.


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-09 15:05 UTC, Ibizugbe commented on src/components/Calculator.js
> +    };
Just as required in this milestone, we are to make use of `useState` hook to manage our state, `props` to pass data around components, and just as I suggested in the previous comments, you need to convert your class components to functional components to make use of the `useState` hook😉.

<img width="780" alt="image" src="https://github.com/MenendezON/math-magicians/assets/64643995/d3a18db3-62b3-4347-abec-011e180a3b18">

2023-08-09 15:05 UTC, Ibizugbe commented on src/components/keypad.js
> +    const items = ['AC', '+/-', '%', '/', '7', '8', '9', 'x', '4', '5', '6', '-', '1', '2', '3', '+', '0', '.', '='];
Currently, when I try to carry out a division operation, an error is displayed which breaks the application, kindly fix this😉.

<img width="1040" alt="image" src="https://github.com/MenendezON/math-magicians/assets/64643995/98bfc38c-907f-483f-95f6-7be09aa849b6">

2023-08-10 11:10 UTC, DammyShittu approved these changes
Hi @MenendezON,

## APPROVED 🟢

## Highlights
✔️ Project met all technical requirements

Great implementation of all the requirements in this milestone. 👏 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

Congratulations! 🎉 

## CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 11:16 UTC, merged